name: Build Sanity Check

on:
    pull_request:
      types:
        - opened
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Prepare Dependencies and Build
        run: make dist
