name: "close-stale-issues-and-prs"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 90
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          debug-only: false
          exempt-all-assignees: true
          operations-per-run: 1000
          stale-issue-message: "This issue has been marked 'stale' after 90 days of inactivity. If there is no further activity, it will be closed in 7 days."
          stale-pr-message: "This PR has been marked 'stale' after 90 days of inactivity. If there is no further activity, it will be closed in 7 days."
